# Generated by Django 5.2.8 on 2025-12-02 08:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busapi', '0002_alter_bus_arrival_past_table_savedroute_favorite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='favorite',
            name='busapi_favorite_user_label_type_uniq',
        ),
        migrations.AlterField(
            model_name='bus_arrival_past',
            name='routeid',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'label', 'type')},
        ),
    ]
